### PR TITLE
Use `github-pages` gem to manage ruby deps

### LINKED ISSUE #4: bump ruby dependencies
heyo,

are you guys still using this at CfA? it's super handy, but it seems like the ruby dependencies aren't up-to-date with what GitHub Pages has installed. the [`github-pages` gem](http://rubygems.org/gems/github-pages) seems to package things up nicely, if you just wanted to install from there.

### PR DESCRIPTION
**Pull request by ajb**
Closes #4

### CODE REVIEW

**Comment by migurski** [comment]
Now I'm debugging my own bad chef recipes. Planning to merge.

**Comment by migurski** [comment]
The short version is that I have no idea how RVM is supposed to work when globally installed on a system.

**Comment by ajb** [comment]
Awesome, don't worry about the delay, we're all busy here too :)

And yeah, I have no idea how RVM is supposed to work, apparently it consists of 50,000 lines of bash scripts. I just `brew install` and bask in my ignorance.

**Comment by migurski** [comment]
Yeah, I've said it before that the Ruby community’s enthusiastic acceptance of completely insane shell tricks is baffling. Anyway I've made some progress; hope to merge up soon.

**Comment by ajb** [comment]
Anything I can do to help get this merged?

**Comment by migurski** [comment]
Hey, thanks for following up! I've finally had a chance to catch up on some papercuts in this project. I remain pretty flummoxed by RVM on Linux, all the way down to questioning why I'd want my Ruby versions managed in the first place and can there just please be one that works from Apt. None of the Ruby people I've talked to have a clue how any of this stuff works either; they just `brew install` and pray like you and me. I'm beginning to doubt the existence of Ruby experts altogether.

I seem to still be using Ruby 1.8 on the Ubuntu server where Jekit lives. [Chef-RVM](https://github.com/fnichol/chef-rvm) appears promising, but I'm not making heads or tails of [the installation guide](https://github.com/fnichol/chef-rvm#-installation).

So, I might put this down for a while again.

**Comment by migurski** [comment]
Two bits of input from Drew:
- “Unfortunately some Linux packages still depend on Ruby 1.8. Rbenv and Chruby are lighter alternatives to RVM (neither replace cd).” ([tweet](https://twitter.com/drewdaraabrams/status/510563638336184320))
- “Or if you want to stay in Ubuntu package land, these are a little funky but do work: [http://brightbox.com/docs/ruby/ubuntu/ …](http://brightbox.com/docs/ruby/ubuntu/)” ([tweet](https://twitter.com/drewdaraabrams/status/510563788857171970))

**Comment by ajb** [comment]
Yeah, I finally switched from RVM to rbenv on my development machine. Feels
good. No Chef experience here either, though.

On Mon, Sep 15, 2014 at 5:34 PM, migurski notifications@github.com wrote:

> Two bits of input from Drew:
> - “Unfortunately some Linux packages still depend on Ruby 1.8. Rbenv
>   and Chruby are lighter alternatives to RVM (neither replace cd).” (
>   tweet https://twitter.com/drewdaraabrams/status/510563638336184320)
> - “Or if you want to stay in Ubuntu package land, these are a little
>   funky but do work: http://brightbox.com/docs/ruby/ubuntu/ …
>   http://brightbox.com/docs/ruby/ubuntu/” (tweet
>   https://twitter.com/drewdaraabrams/status/510563788857171970)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/git-jekyll-preview/pull/5#issuecomment-55662661
> .

## 

Adam Becker
510.928.9111
@AdamJacobBecker

**Comment by migurski** [comment]
Also from Andy: https://gist.github.com/gravitystorm/c9dc9cac9d00b31028bb

**Comment by migurski** [comment]
I ended up using the Ruby 1.9.3 & Apt route from @gravitystorm, merged now.

**Comment by ajb** [comment]
Totally badass, thanks @migurski!

**Pull request merged**
